routes/web.php
<?php

use App\Helper\MyDate;
use App\Models\Event;
use App\Models\Theme;
use App\Models\Category;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Auth::routes(['register' => false]);

Route::prefix('admin')->group(function () {
    Route::post('/file/upload', 'Admin\FileController@upload')->name('admin.fileUpload');
	Route::post('/file/uploadAudio', 'Admin\FileController@uploadAudio')->name('admin.fileUploadAudio');
    Route::post('/file/editorUpload', 'Admin\FileController@editorUpload')->name('admin.fileEditorUpload');
    Route::post('/file/uploadCropped', 'Admin\FileController@uploadCropped')->name('admin.fileUploadCropped');
    Route::post('/file/delete', 'Admin\FileController@delete')->name('admin.fileDelete');
    Route::post('/file/deleteDropfile', 'Admin\FileController@deleteDropfile')->name('admin.dropfileDelete');
    Route::get('/file/syncImages', 'Admin\FileController@syncImages')->name('admin.syncImages');

    Route::get('/events', 'Admin\EventController@listEvents')->name('admin.eventList');
	Route::get('/events/archive', 'Admin\EventController@archive')->name('admin.eventArchive');
	Route::get('/events/archive/search', 'Admin\EventController@archive')->name('admin.eventArchiveSearch');
    Route::get('/events/edit', 'Admin\EventController@edit')->name('admin.eventNew');
    Route::get('/events/edit/{id?}', 'Admin\EventController@edit')->name('admin.eventEdit');
    Route::get('/events/delete/{id}', 'Admin\EventController@delete')->name('admin.eventDelete');
	Route::post('/events/template', 'Admin\EventController@template')->name('admin.eventTemplateSelect');
	Route::post('/events/store/{id?}', 'Admin\EventController@store')->name('admin.eventStore');
	Route::post('/events/override/{id?}', 'Admin\EventController@override')->name('admin.eventOverride');
    Route::post('/events/checkForPeriodicDate', 'Admin\EventController@checkForPeriodicDate')->name('admin.checkForPeriodicDate');

	Route::get('/eventsTemplate', 'Admin\EventTemplateController@index')->name('admin.eventTemplateList');
	Route::get('/eventsTemplate/edit', 'Admin\EventTemplateController@edit')->name('admin.eventTemplateNew');
	Route::get('/eventsTemplate/edit/{id?}', 'Admin\EventTemplateController@edit')->name('admin.eventTemplateEdit');
	Route::get('/eventsTemplate/delete/{id}', 'Admin\EventTemplateController@delete')->name('admin.eventTemplateDelete');
	Route::post('/eventsTemplate/store/{id?}', 'Admin\EventTemplateController@store')->name('admin.eventTemplateStore');

	Route::get('/eventsPeriodic', 'Admin\EventPeriodicController@index')->name('admin.eventPeriodicList');
    Route::get('/eventsPeriodic/edit', 'Admin\EventPeriodicController@edit')->name('admin.eventPeriodicNew');
    Route::get('/eventsPeriodic/edit/{id?}', 'Admin\EventPeriodicController@edit')->name('admin.eventPeriodicEdit');
    Route::get('/eventsPeriodic/delete/{id}', 'Admin\EventPeriodicController@delete')->name('admin.eventPeriodicDelete');
    Route::post('/eventsPeriodic/store/{id?}', 'Admin\EventPeriodicController@store')->name('admin.eventPeriodicStore');

    Route::get('/users', 'Admin\UserController@index')->name('admin.userList');
    Route::get('/users/edit', 'Admin\UserController@edit')->name('admin.userNew');
    Route::get('/users/edit/{id?}', 'Admin\UserController@edit')->name('admin.userEdit');
    Route::get('/users/delete/{id}', 'Admin\UserController@delete')->name('admin.userDelete');
    Route::post('/users/store/{id?}', 'Admin\UserController@store')->name('admin.userStore');
	Route::get('/users/reset', 'Admin\UserController@reset')->name('admin.userReset');

    Route::get('/categories', 'Admin\CategoryController@index')->name('admin.categoryList');
    Route::get('/categories/edit', 'Admin\CategoryController@edit')->name('admin.categoryNew');
    Route::get('/categories/edit/{id?}', 'Admin\CategoryController@edit')->name('admin.categoryEdit');
    Route::get('/categories/delete/{id}', 'Admin\CategoryController@delete')->name('admin.categoryDelete');
    Route::post('/categories/store/{id?}', 'Admin\CategoryController@store')->name('admin.categoryStore');

    Route::get('/themes', 'Admin\ThemeController@index')->name('admin.themeList');
    Route::get('/themes/edit', 'Admin\ThemeController@edit')->name('admin.themeNew');
    Route::get('/themes/edit/{id?}', 'Admin\ThemeController@edit')->name('admin.themeEdit');
    Route::get('/themes/delete/{id}', 'Admin\ThemeController@delete')->name('admin.themeDelete');
    Route::post('/themes/store/{id?}', 'Admin\ThemeController@store')->name('admin.themeStore');

    Route::get('/pages', 'Admin\PageController@index')->name('admin.pageList');
    Route::get('/pages/edit', 'Admin\PageController@edit')->name('admin.pageNew');
    Route::get('/pages/edit/{id?}', 'Admin\PageController@edit')->name('admin.pageEdit');
    Route::get('/pages/delete/{id}', 'Admin\PageController@delete')->name('admin.pageDelete');
    Route::post('/pages/store/{id?}', 'Admin\PageController@store')->name('admin.pageStore');

	Route::get('/musicStyles', 'Admin\MusicStyleController@index')->name('admin.musicStyleList');
	Route::get('/musicStyles/edit', 'Admin\MusicStyleController@edit')->name('admin.musicStyleNew');
	Route::get('/musicStyles/edit/{id?}', 'Admin\MusicStyleController@edit')->name('admin.musicStyleEdit');
	Route::get('/musicStyles/delete/{id}', 'Admin\MusicStyleController@delete')->name('admin.musicStyleDelete');
	Route::post('/musicStyles/store/{id?}', 'Admin\MusicStyleController@store')->name('admin.musicStyleStore');

	Route::get('/addresses', 'Admin\AddressController@listAll')->name('admin.addressList');
	Route::get('/addresses/show/{id}', 'Admin\AddressController@show')->name('admin.addressShow');
	Route::get('/addresses/edit', 'Admin\AddressController@edit')->name('admin.addressNew');
	Route::get('/addresses/edit/{id?}', 'Admin\AddressController@edit')->name('admin.addressEdit');
	Route::get('/addresses/delete/{id}', 'Admin\AddressController@delete')->name('admin.addressDelete');
	Route::post('/addresses/store/{id?}', 'Admin\AddressController@store')->name('admin.addressStore');

	Route::get('/addressCategories', 'Admin\AddressCategoryController@index')->name('admin.addressCategoryList');
//	Route::get('/addressCategories/show/{id}', 'Admin\AddressCategoryController@show')->name('admin.addressCategoryShow');
	Route::get('/addressCategories/edit', 'Admin\AddressCategoryController@edit')->name('admin.addressCategoryNew');
	Route::get('/addressCategories/edit/{id?}', 'Admin\AddressCategoryController@edit')->name('admin.addressCategoryEdit');
	Route::get('/addressCategories/delete/{id}', 'Admin\AddressCategoryController@delete')->name('admin.addressCategoryDelete');
	Route::post('/addressCategories/store/{id?}', 'Admin\AddressCategoryController@store')->name('admin.addressCategoryStore');

	Route::get('/newsletter', 'Admin\NewsletterController@index')->name('admin.newsletterList');
	Route::get('/newsletter/edit/{campaignId?}', 'Admin\NewsletterController@edit')->name('admin.newsletterEdit');
	Route::get('/newsletter/delete/{campaignId}', 'Admin\NewsletterController@delete')->name('admin.newsletterDelete');
	Route::post('/newsletter/process', 'Admin\NewsletterController@process')->name('admin.newsletterProcess');
	Route::post('/newsletter/preview', 'Admin\NewsletterController@preview')->name('admin.newsletterPreview');
	Route::post('/newsletter/create', 'Admin\NewsletterController@create')->name('admin.newsletterCreate');
	Route::post('/newsletter/check', 'Admin\NewsletterController@check')->name('admin.newsletterCheck');
	Route::post('/newsletter/test', 'Admin\NewsletterController@test')->name('admin.newsletterTest');
	Route::post('/newsletter/send', 'Admin\NewsletterController@send')->name('admin.newsletterSend');
	Route::get('/newsletter/members/{segmentId}', 'Admin\NewsletterController@getMembers')->name('admin.newsletterMembers');

	Route::get('/messages', 'Admin\MessageController@getList')->name('admin.messageList');
	Route::get('/messages/show/{id}', 'Admin\MessageController@show')->name('admin.messageShow');
	Route::get('/messages/edit', 'Admin\MessageController@edit')->name('admin.messageNew');
	Route::get('/messages/edit/{id?}', 'Admin\MessageController@edit')->name('admin.messageEdit');
	Route::get('/messages/delete/{id}', 'Admin\MessageController@delete')->name('admin.messageDelete');
	Route::post('/messages/store/{id?}', 'Admin\MessageController@store')->name('admin.messageStore');

	Route::get('/services/syncImages', 'Admin\ServiceController@syncImages')->name('admin.service.syncImages');
	Route::get('/services/makeThumbs', 'Admin\ServiceController@makeThumbs')->name('admin.service.makeThumbs');
    Route::get('/services/sanitizeImageDB', 'Admin\ServiceController@sanitizeImageDB')->name('admin.service.sanitizeImageDB');
    Route::get('/services/cropImages', 'Admin\ServiceController@cropImages')->name('admin.service.cropImages');
	Route::get('/services/syncAudios', 'Admin\ServiceController@syncAudios')->name('admin.service.syncAudios');
	Route::get('/services/sanitizeFilePermissions', 'Admin\ServiceController@sanitizeFilePermissions')->name('admin.service.sanitizeFilePermissions');
	Route::get('/services/browserTestReport', 'Admin\ServiceController@browserTestReport')->name('admin.service.browserTestReport');
	Route::get('/dusk/runBrowserTest', 'Admin\DuskController@runBrowserTest')->name('admin.dusk.runBrowserTest');
	Route::get('/terminal/{view?}', 'Admin\TerminalController@index')->name('admin.terminal.index');

app/Models/Event.php
<?php

namespace App\Models;

use Carbon\Carbon;
use App\Models\Image;
use App\Helper\MyDate;
use App\Models\Ext\HasUser;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Database\Eloquent\Builder;
use App\Repositories\EventEntityRepository;
use App\Repositories\EventPeriodicRepository;

/**
 * Class Event
 */
class Event extends Model
{
	use Sortable, HasUser;

	public $sortable = [
		'category',
		'title',
		'event_date',
	];

	/**
     * @var string
     */
    protected $table = 'event';
    /**
     * @var array
     */
    protected $fillable = ['title', 'subtitle'];
    protected $dates = ['created_at','updated_at'];
	protected $eventLink;
	public $descriptionSanitized;
	public $descriptionText;

	public static function boot() {
		parent::boot();
		Event::retrieved(function($entity) {
			$wrapper = '<div class="row embed-responsive-wrapper text-center"><div class="embed-responsive embed-responsive-16by9 m-0 p-0">%%</div></div>';
			$entity->descriptionSanitized = preg_replace("/(<iframe[^>]+><\/iframe>)/i", str_replace('%%','$1', $wrapper), $entity->description);
			$entity->descriptionText = strip_tags(preg_replace('/<br[ ]?[\/]?>/i',"\n", $entity->description));
		});
	}

	/**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function theme()
    {
        return $this->belongsTo('App\Models\Theme');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany('App\Models\Images');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function audios()
    {
        return $this->hasMany('App\Models\Audios');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function videos()
    {
        return $this->hasMany('App\Models\Videos');
    }

    /**
     * @param string $value
     * @return array
     */
    public function getLinksAttribute($value = '')
    {
        if('' !== $value) {
            return collect(preg_split("/[\n\r]+/", $value));
        }
    }

	public function getEventLinkAttribute()
	{
		return route('events.show', $this);
	}

	/**
	 * @param string $value
	 * @return array
	 */
	public function getDescriptionAttribute($value = '')
	{
		if('' !== $value) {
			return preg_replace(['/^<p>(<br[ ]?[\/]?>){1,}/i','/(<br[ ]?[\/]?>){1,}<\/p>$/i'],['<p>','</p>'], trim($value));
		}
	}

	public function scopeAllActual(Builder $query)
	{
		$result = $query
			->with(['category','theme'])
			->where('is_published', 1)
			->whereDate('event_date','>=', MyDate::getUntilValidDate())
			->orderBy('event_date')
		;

		return $result;
	}

	public function scopeAllActualMerged()
	{
		$repo			= new EventPeriodicRepository();
		$repoEntity		= new EventEntityRepository();

		$periodicEvents	= $repo->getAllPeriodicDates(true, true);
		$datedEvents	= self::allActual()->get()->keyBy('event_date');

		$mapped	= $repoEntity->mapToEventEntityCollection($datedEvents);
		$merged	= $periodicEvents->merge($mapped)->sortKeys();

		return $merged;
	}

	public static function eventsForNewsletter(Carbon $from, Carbon $until)
	{
		$filtered = self::allActualMerged()->filter(function ($event) use ($from, $until) {
			return ($event->getEventDate()->between($from, $until));
		});
		return $filtered;
	}

	/*
		public function scopeAllActualByDateKey(Builder $query, $slug = null)
		{
			$result = $query
				->where('event_date','>=', MyDate::getUntilValidDate())
				->when($slug, function($query) use ($slug) {
					return $query->where('slug', $slug);
				});

			return $result;
		}
	*/
	public function scopeByCategorySlug(Builder $query, $slug, $sinceToday = true)
	{
		$result = $query
			->with(['category','theme'])
			->where('is_published', 1)
			->when($sinceToday, function($query) {
				return $query->whereDate('event_date','>=', MyDate::getUntilValidDate());
			})
			->whereHas('category', function($query) use ($slug) {
				$query->where('slug', $slug);
			});
		return $result;
	}

	public function scopeByThemeSlug(Builder $query, $slug, $sinceToday = true)
	{
		$result = $query
			->with(['category','theme'])
			->where('is_published', 1)
			->when($sinceToday, function($query) {
				return $query->whereDate('event_date','>=', MyDate::getUntilValidDate());
			})
			->whereHas('theme', function($query) use ($slug) {
				$query->where('slug', $slug);
			});

		return $result;
	}

	public function scopeMergedByCategorySlug(Builder $query, $slug, $sinceToday = true)
	{
		$repo 		= new EventPeriodicRepository();
		$repoEntity	= new EventEntityRepository();

		$periodicEvents	= $repo->getAllPeriodicDatesByCategory($slug);
		$datedEvents = $this->scopeByCategorySlug($query, $slug, $sinceToday)->get()->keyBy('event_date');

		$mappedEvents = $repoEntity->mapToEventEntityCollection($datedEvents);
//		$merged = $periodicEvents->merge($mappedEvents)->sortKeys()->paginate(config('event.paginationLimit'));
		$merged = $periodicEvents->merge($mappedEvents)->sortKeys();

		return $merged;
	}

	public function scopeMergedByDate(Builder $query, $date )
	{
		$repo 	= new EventPeriodicRepository();
		$event	= self::whereDate('event_date', $date)->first();

		if( $event ) {
			return $event;
		}

		$periodicEvent	= $repo->getPeriodicEventByDate($date);
		if( $periodicEvent ) {
			return $periodicEvent;
		}
		return null;
	}

	public function scopeMergedByDateAndCategory(Builder $query, $date, $slug )
	{
		$repo 		= new EventPeriodicRepository();
		$repoEntity	= new EventEntityRepository();

		$event = self::whereDate('event_date', $date)
			->where('is_published', 1)
			->whereHas('category', function($query) use ($slug) {
				$query->where('slug', $slug);
			})
			->first();
		if($event) {
			$entity = $repoEntity->mapToEventEntity($event, $date);
			if($entity) {
				return $entity;
			}
		}

		$periodicEvent	= $repo->getPeriodicEventByDateAndCategory($date, $slug);
		if($periodicEvent) {
			return $periodicEvent;
		}
		return null;
	}

	public function scopeMergedByDateAndTheme(Builder $query, $date, $slug )
	{
		$repo 		= new EventPeriodicRepository();
		$repoEntity	= new EventEntityRepository();

		$event = self::whereDate('event_date', $date)
			->where('is_published', 1)
			->whereHas('theme', function($query) use ($slug) {
				$query->where('slug', $slug);
			})
			->first();
		if($event) {
			$entity = $repoEntity->mapToEventEntity($event, $date);
			if($entity) {
				return $entity;
			}
		}

		$periodicEvent	= $repo->getPeriodicEventByDateAndCategory($date, $slug);
		if($periodicEvent) {
			return $periodicEvent;
		}
		return null;
	}

	public function scopeMergedByThemeSlug(Builder $query, $slug, $sinceToday = true)
	{
		$repo 		= new EventPeriodicRepository();
		$repoEntity	= new EventEntityRepository();

		$periodicEvents	= $repo->getAllPeriodicDatesByTheme($slug);
		$datedEvents = $this->scopeByThemeSlug($query, $slug, $sinceToday)->get()->keyBy('event_date');

		$mappedEvents = $repoEntity->mapToEventEntityCollection($datedEvents);
//		$merged = $periodicEvents->merge($mappedEvents)->sortKeys()->paginate(config('event.paginationLimit'));
		$merged = $periodicEvents->merge($mappedEvents)->sortKeys();

		return $merged;
	}
}

resources/views/admin/addresses.blade.php
@extends('layouts.admin')

@section('content')
    @include('components.add')
    <br>
    {{ $data->links() }}
    {!! form($addressCategoryForm) !!}

    <table class="table-responsive-sm">
        <tr class="table table-striped table-sm">
            <th scope="col">ID</th>
            <th scope="col" class="col-sm-auto">@sortablelink('addressCategory.name','Type')</th>
            <th scope="col" class="col-sm-auto">@sortablelink('email')</th>
            <th scope="col" class="d-none d-sm-table-cell">TagID</th>
            <th scope="col" class="d-none d-sm-table-cell">@sortablelink('created_at','Erstellt')</th>
            <th scope="col" colspan="2">#</th>
        </tr>
    @foreach ($data as $item)
        <tr>
            <td>{{ $item->id }} </td>
            <td class="col-sm-auto">{{ $item->addressCategory->name }}</td>
            <td class="col-sm-auto">{{ $item->email }}</td>
            <td class="d-none d-sm-table-cell">{{ $item->tag_id }}</td>
            <td class="d-none d-sm-table-cell">{{ $item->created_at->format('d.m.Y H:i') }}</td>

            @include('admin.templates.action')
        </tr>
    @endforeach
    </table>
    <div>
        {{ $data->links() }}
    </div>
@endsection

resources/views/admin/eventPeriodics.blade.php
@extends('layouts.admin')

@section('content')
    @include('components.add')
    <br>
    {{ $data->links() }}
    <table class="table-responsive-sm">
        <tr class="table table-striped table-sm">
            <th scope="col">ID</th>
            <th scope="col" class="col-sm-auto">Titel</th>
            <th scope="col">Termin</th>
            <th scope="col" class="d-none d-sm-table-cell">CreatedBy</th>
            <th scope="col" class="d-none d-sm-table-cell">UpdatedBy</th>
            <th scope="col" class="d-none d-sm-table-cell">Publiziert</th>
            <th scope="col" colspan="2">#</th>
        </tr>
    @foreach ($data as $item)
        <tr>
            <td>{{ $item->id }} </td>
            <td class="col-sm-auto">{{ $item->title }}</td>
            <td>{{ $item->periodicPosition->name }} {{ $item->periodicWeekday->name_de }}</td>
            <td class="text-center d-none d-sm-table-cell">@if($item->createdBy) {{ $item->createdBy->username }} @else <br> @endif </td>
            <td class="text-center d-none d-sm-table-cell">@if($item->updatedBy) {{ $item->updatedBy->username }} @else <br> @endif </td>
            <td class="text-center d-none d-sm-table-cell"><i class="@if($item->is_published) ion-md-checkmark-circle-outline text-success @else ion-md-close-circle-outline text-danger @endif"></i></td>

            @include('admin.templates.action')
        </tr>
    @endforeach
    </table>
    {{ $data->links() }}
@endsection

resources/views/admin/eventTemplates.blade.php
@extends('layouts.admin')

@section('content')
    @include('components.add')
    <br>
    {{ $data->links() }}
    <table class="table-responsive-sm mbs">
        <tr class="table table-striped table-sm">
            <th scope="col">ID</th>
            <th scope="col" class="col-sm-auto">Titel</th>
            <th scope="col" class="d-none d-sm-table-cell">CreatedBy</th>
            <th scope="col" class="d-none d-sm-table-cell">UpdatedBy</th>
            <th scope="col" colspan="2">#</th>
        </tr>
    @foreach ($data as $item)
        <tr>
            <td>{{ $item->id }} </td>
            <td class="col-sm-auto">{{ $item->title }}</td>
            <td class="text-center d-none d-sm-table-cell">@if($item->createdBy) {{ $item->createdBy->username }} @else <br> @endif </td>
            <td class="text-center d-none d-sm-table-cell">@if($item->updatedBy) {{ $item->updatedBy->username }} @else <br> @endif </td>

            @include('admin.templates.action')
        </tr>
    @endforeach
    </table>
    {{ $data->links() }}
@endsection

resources/views/admin/messages.blade.php
@extends('layouts.admin')

@section('extra-headers')
    <script type="text/javascript" src="{{ asset('js/admin.js') }}" charset="UTF-8"></script>
@endsection

@section('content')

    @include('components.add')
    @include('admin.form.filter.messages')
    <br>
    {{ $data->links() }}
    <table class="table-responsive-sm">
        <tr class="table table-striped table-sm">
            <th scope="col">ID</th>
            <th scope="col" class="col-sm-auto">@sortablelink('musicStyle.name', 'Musikrichtung')</th>
            <th scope="col" class="d-none d-sm-table-cell">@sortablelink('email')</th>
            <th scope="col" class="d-none d-sm-table-cell">@sortablelink('name')</th>
            <th scope="col" class="d-none d-sm-table-cell">Message</th>
            <th scope="col" class="d-none d-sm-table-cell">@sortablelink('created_at','Erstellt')</th>
            <th scope="col" colspan="2">#</th>
        </tr>
    @foreach ($data as $item)
        <tr>
            <td>{{ $item->id }} </td>
            <td class="col-sm-auto">@if($item->musicStyle){{ $item->musicStyle->name }}@endif</td>
            <td class="d-none d-sm-table-cell">{{ $item->email }}</td>
            <td class="d-none d-sm-table-cell">{{ $item->name }}</td>
            <td class="d-none d-sm-table-cell">{{ \Illuminate\Support\Str::limit($item->message, 30) }}</td>
            <td class="d-none d-sm-table-cell">{{ $item->created_at->format('d.m.Y H:i') }}</td>
            @include('admin.templates.action.show')

            @include('admin.templates.action.delete')
        </tr>
    @endforeach
    </table>
    {{ $data->links() }}
@endsection

resources/views/admin/musicStyles.blade.php
@extends('layouts.admin')

@section('content')
    @include('components.add')
    <br>
    {{ $data->links() }}
    <table class="table-responsive-sm">
        <tr class="table table-striped table-sm">
            <th scope="col">ID</th>
            <th scope="col" class="col-sm-auto">@sortablelink('name')</th>
            <th scope="col" class="d-none d-sm-table-cell">Slug</th>
            <th scope="col" colspan="2">#</th>
        </tr>
        @foreach ($data as $item)
            <tr>
                <td>{{ $item->id }} </td>
                <td class="col-sm-auto">{{ $item->name }}</td>
                <td class="d-none d-sm-table-cell">{{ $item->slug }}</td>

                @include('admin.templates.action')
            </tr>
        @endforeach
    </table>
    {{ $data->links() }}
@endsection

resources/views/admin/service.blade.php
@extends('layouts.admin')

@section('content')
    <div class="service col-12">
        <h3>Service</h3>
        <div class="serviceWrapper m-3">
            <pre>{!! $output !!}</pre>
        </div>
    </div>
@endsection

resources/views/admin/themes.blade.php
@extends('layouts.admin')

@section('content')
    @include('components.add')
    <br>
    {{ $data->links() }}
    <table class="table-responsive-sm">
        <tr class="table table-striped table-sm">
            <th scope="col">ID</th>
            <th scope="col" class="col-sm-auto">Name</th>
            <th scope="col" class="d-none d-sm-table-cell">Slug</th>
            <th scope="col" class="d-none d-sm-table-cell">Default EventTime</th>
            <th scope="col" class="d-none d-sm-table-cell">Default EventPrice</th>
            <th scope="col" class="d-none d-sm-table-cell">Enabled</th>
            <th scope="col" colspan="2">Aktion</th>
        </tr>
    @foreach ($data as $item)
        <tr>
            <td>{{ $item->id }} </td>
            <td class="col-sm-auto">{{ $item->name }}</td>
            <td class="d-none d-sm-table-cell">{{ $item->slug }}</td>
            <td class="d-none d-sm-table-cell">{{ $item->default_time }}</td>
            <td class="d-none d-sm-table-cell">{{ $item->default_price }}</td>
            <td class="text-center d-none d-sm-table-cell"><i class="@if($item->is_published) ion-md-checkmark-circle-outline text-success @else ion-md-close-circle-outline text-danger @endif"></i></td>

            @include('admin.templates.action')
        </tr>
    @endforeach
    </table>
    {{ $data->links() }}
@endsection

resources/views/admin/users.blade.php
@extends('layouts.admin')

@section('content')
    @if( auth()->user() && auth()->user()->is_super_admin )
        @include('components.add')
    @endif

    <br>
    {{ $data->links() }}
    <div class="table-responsive-sm">
        <table class="table table-striped table-sm">
            <tr>
                <th scope="col">ID</th>
                <th scope="col" class="col-sm-auto">@sortablelink('username')</th>
                <th scope="col" class="d-none d-sm-table-cell">@sortablelink('email')</th>
                <th scope="col" class="d-none d-sm-table-cell">@sortablelink('last_login','Last Login')</th>
                <th scope="col" class="d-none d-sm-table-cell">@sortablelink('enabled','Aktiv')</th>
                <th scope="col" colspan="2">#</th>
            </tr>
        @foreach ($data as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td class="col-sm-auto">{{ $item->username }}</td>
                <td class="d-none d-sm-table-cell">{{ $item->email }}</td>
                <td class="d-none d-sm-table-cell">@if($item->last_login) {{ $item->last_login->format('d.m.Y H:i') }} @endif</td>
                <td class="d-none d-sm-table-cell"><i class="@if($item->enabled) ion-md-checkmark-circle-outline text-success @else ion-md-close-circle-outline text-danger @endif"></i></td>

                @include('admin.templates.action')
            </tr>
        @endforeach
        </table>
    </div>
    {{ $data->links() }}
@endsection